### ISSUE TITLE
Add logo on RWW pages 

### ISSUE THREAD

**Issue by idealley** [EuropeanRespiratorySociety/ERSMainWebsite#26]
We need to see the following logo: 
![respiratory-worldwide_final](https://cloud.githubusercontent.com/assets/917006/22010665/f567a7ec-dc8a-11e6-830d-429b55e34be6.jpg)

On the respiratory world wide pages (we can put it in the right column in the blue pannel, but we need to change the background color to white (`default`)... as the background of the image is white) maybe add a `<hr>` betwenn the image and the logo/description.

Then I would use the image as a second flag over the pictures in the page http://ersnet.app/the-society/news/respiratory-worldwide. The logo needs to be small. This is a little bit tricky.

You need to add it in `elements/cards/image.blade.php` there are a few flags that are set conditionally like the `fully booked` one.

**Comment by tasanoers** [comment]
https://github.com/EuropeanRespiratorySociety/ERSTemplate-dev/issues/21

**Comment by tasanoers** [comment]
**Current situation:**
image.blade.php ---line 39
```
    @if($item->category)
        @if($item->category->title == "Respiratory Worldwide" )
            <span class="label"><img style="position:relative; bottom:0; top:0; left:10px; transform:initial; padding:0; margin-bottom: -1px;" src="../images/news/flag-rww.jpg" alt=""></span>
        @endif
    @endif

```

**Doesn't working like this:**
labels.less--line 27

#ersMainWebsite &{
```
	.card-event, .hover-gradation, .hover-gradation-dark, .card-home {
        .label{
            position: absolute;
            right: 0;
            z-index: 100;
            font-weight: 100;
            font-size: 17px;
            font-style: italic;
            padding: 5px 10px 2px;
            top: auto;
            left: auto;
            
            &:nth-child(2){
            top:auto;
            bottom:0;
            }

            .label-image{
                position: relative;
                bottom: 0;
                top: 0;
                left: 10px;
                transform: initial;
                padding: 0;
            }
        }


        .label-right{
            display: inline;
            position: absolute;
            color: #ffffff;
            top:0;
            left:0;
            padding: 2px 10px 2px;

            &:nth-child(2){
            top:auto;
            bottom:0;
            }
        }

    }

}
```

**Comment by tasanoers** [comment]
18/01/2017
Finished modification ,  commited on branch Feature-#26 (and on Feature-#21 at erstemplate)
and these 2 branches are pushed on Github's master branch.
