### ISSUE TITLE
Awards pages

### ISSUE THREAD

**Issue by idealley** [EuropeanRespiratorySociety/ERSMainWebsite#29]
Here is the new structure that we need to add to the main menu:

 -  Awards (top page)
    - Gold Medals (second level subpage)
        - GM in asthma (third level sub page)
        - GM in COPD
        - GM in IPF
    - Special Honours (Beth has built this section so you can see what we mean: https://www.ersnet.org/the-society/who-we-are/awards/ers-awards-special-honours)
        - Presidential Award previous winners
        - Congress Chair Award previous winners
        - Educational Award previous winners
        - ERS Assembly Lifetime Achievement Award previous winners
        - Sadoul Lecturer Award previous winners
        - Yernault Lecturer Award previous winners
        - Cournand Lecturer Award previous winners
    - Research Excellence
        - ERS Romain Pauwels Research Award
        - ERS Excellence Award for Research in Cystic Fibrosis
        - Sir John Vane Grant for Best Recent Publication in Pulmonary Vascular Research

Only `Awards` will be visible where it can now be found in the menu. The `Awards` category already exists in CloudCMS. 

1. We need to create 3 sub categories (`Gold Medals`, `Special Honours` and `Research Excellence`) Beth has created and article/item, for `Special  Honours` and she has created single items that are linked from it. We need to add the category to this items when it will be created. The `Special  Honours` single item needs to be deleted to avoid conflicts with the slug. Check if she did not create other pages as well.
2. The awards is managed by the `GeneralController` with the method `awards` we can add 3 methods in this controller, one for each new sub page/category. (`goldMedals`, `specialHonours`, `researchExcellence`)
3. Edit the navigation file to add the new menu entries. Do not forget the attributes for it not to display.
4. We need to modify the `society.awards` view to add the boxes to the sub categories as per the attached document bellow. The boxes need to display only on this page (use the slug to check on which page we are).
5. Re-use the same view for the subcategories. In my opinion, the boxes in the sub-views need to be created in markdown in the CMS. We create boxes only for the awards landing pages. Use the same boxes as the news page.
6. Edit the routes file to add the new routes `awards/gold-medals`, `awards/special-honours` and `awards/research-excellence` 

[Awards_page_plan_Final.docx](https://github.com/EuropeanRespiratorySociety/ERSMainWebsite/files/711229/Awards_page_plan_Final.docx)
gories

**Comment by tasanoers** [comment]
```
    Route::get('awards/gold-medals', 'GeneralController@goldMedals'); 
    Route::get('awards/gold-medals/{slug}', 'GeneralController@show'); 
```

**Comment by tasanoers** [comment]
http/middleware/Navigation.php
```
                        $menu->awards->add('Gold Medals', 'the-society/who-we-are/awards/gold-medals')
                                                        ->link->attr(array('style' => 'display:none'));
```

**Comment by tasanoers** [comment]
@if($category->title == "Awards")  contents of theree boxes   @endif

**Comment by idealley** [comment]
Looks good to me!

**Comment by tasanoers** [comment]
❓ 

The three second category pages are shown in 2 categories mode.
(gold medals, special honours and Research excellence)

**Comment by tasanoers** [comment]
❗️ 
An error on http://ersnet.app/the-society/news/respiratory-matters
On the branch #26 and on my master branch also

> ErrorException in MakeWellFormed.php line 567:
> Attempt to assign property of non-object

**Comment by tasanoers** [comment]
❗️ 
The three new categories under the Awards page have two columns style by default,
like this page : http://ersnet.app/the-society/who-we-are/ers-governance-and-transparency
-> Because they are in the third category , I guess ( It is set "The article where is on the 3rd category = Two columns" )

**Comment by idealley** [comment]
This can easily be changed as it is a parameter. Are you using the view
`awards`? Did you create the routes? As this behaviour looks like the
behaviour of an article `awards/{slug}`

**Comment by tasanoers** [comment]
route.php
```sh
    Route::get('awards', 'GeneralController@awards'); 
    Route::get('awards/{slug}', 'GeneralController@show'); 
    Route::get('awards/gold-medals', 'GeneralController@goldMedals'); 
    Route::get('awards/gold-medals/{slug}', 'GeneralController@goldMedals'); 
    Route::get('awards/special-honours', 'GeneralController@specialHonours'); 
    Route::get('awards/special-honours/{slug}', 'GeneralController@specialHonours'); 
    Route::get('awards/research-excellence', 'GeneralController@researchExcellence'); 
    Route::get('awards/research-excellence/{slug}', 'GeneralController@researchExcellence'); 
```

**Comment by idealley** [comment]
Ok looks good to me.

Do you return the correct view then? If so, did you create the `category` in Cloud CMS? and did you delete the `article`. If both exist, it will created unexpected behaviours as two items in cloud cms will have the same `slug`, thus you will not know which item you are getting, (most likely the `article`as it is the oldest. )

**Comment by tasanoers** [comment]
```sh
  /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function goldMedals()
    { 
        $results = $this->CC->getItem('goldMedals');
        $item = $this->CC->parseItems($results['rows']);
        $params['item'] =  (object) $item[0]; 

        if(!$item[0]->url || !$item[0]->uri){
            $this->CC->setCanonical($item[0]->_qname);
        }

        $results = $this->CC->getCategory($item[0]->_qname);
        $items = $this->CC->parseItems($results['rows']);
        $params['items'] =  $items;

        return view('society.gold-medals')->with($params);
    }

```

**Comment by tasanoers** [comment]
Now there is no category title that has the same title as the article's one.
(There was special honours that Beth created but I removed. It seems she created only that)

New  3 categories exist in the cloudcms. (gold medals, special honours..) and the each description ($item->body)is on each category.

And I created new 3files in 'the society' folders .

**Comment by idealley** [comment]
You could have used the same view: `awards` with a conditional check to find out if it is the award category or the sub categories. 

Like this you do not repeat code

**Comment by idealley** [comment]
Ok do not worry we will check that tomorrow, so that I can understand better the problem

**Comment by tasanoers** [comment]
Yes , it's better that we check tomorrow ...    Anyway, Thanks a lot for your advices !

**Comment by tasanoers** [comment]
:o:

$results = $this->CC->getItem('**gold-medals**');
↑getItemの中はslug の値を書くこと


> view for gold medals　at `GeneralController.php
> `
>   ```sh
>   /**
>      * Display a listing of the resource.
>      *
>      * @return \Illuminate\Http\Response
>      */
>     public function goldMedals()
>     { 
>         $results = $this->CC->getItem('goldMedals');
>         $item = $this->CC->parseItems($results['rows']);
>         $params['item'] =  (object) $item[0]; 
> 
>         if(!$item[0]->url || !$item[0]->uri){
>             $this->CC->setCanonical($item[0]->_qname);
>         }
> 
>         $results = $this->CC->getCategory($item[0]->_qname);
>         $items = $this->CC->parseItems($results['rows']);
>         $params['items'] =  $items;
> 
>         return view('society.gold-medals')->with($params);
>     }
> 
> ```

**Comment by tasanoers** [comment]
#### Memo for styles of Award list on Special Honours

1.  Like Fellowships page:  https://www.ersnet.org/professional-development/fellowships

```sh
-----

[Short-Term Research Fellowships](professional-development/fellowships/short-term-research-training-fellowships)

-----
```

2.  Back slash and dash    /-

`\- [Presidential Award](https://www.ersnet.org/the-society/who-we-are/awards/presidential-award-winners)`
