### ISSUE TITLE
News article page - Exec Director of FIRS 

### ISSUE THREAD

**Issue by LAndersonERS** [EuropeanRespiratorySociety/ERSMainWebsite#3]
@idealley @rtanabe1027 

[This](https://new.ersnet.org/the-society/news/call-for-applications:-executive-director-of-firs) page is showing numbering in sections - on cloud cms it shows 1,2,3,4 but on the front page it shows 1,1,1,1

**Comment by idealley** [comment]
Actually this subheadings are not lists, thus the `.` should be escaped with `\` . The final numbering looks like:
    1\. the text

Additionally I have changed the `\**title**` which creates bold text to \#### which is a subheading (h4) and is semantically better. 

I have also added the special subheading `#### &nbsp; {.no-break}` to prevent a heading to be at the bottom of the first column. The actual amount of `#` does not matter.
