### ISSUE TITLE
Junior (Early Career member) page

### ISSUE THREAD

**Issue by idealley** [EuropeanRespiratorySociety/ERSMainWebsite#34]
Create the page under leadership

Change the link -> junior to early carer in the right side menu, change the url as well.

**Comment by idealley** [comment]
Text:

### Early Career Members Committee
 
The Early Career Members Committee (ECMC) represents all ERS members under 40. The committee ensures that early career members are supported in their career and professional development and that their interests are represented across the Society. It also promotes the highest standards of evidence-based respiratory education in Europe.
 
Early career members are welcome to join meetings held at the Lung Science Conference and the ERS International Congress to help shape the work of the Society and find out more about activities they can get involved with.

**Comment by tasanoers** [comment]
routes.php
