### ISSUE TITLE
Rules & Regulation button

### ISSUE THREAD

**Issue by idealley** [EuropeanRespiratorySociety/ERSMainWebsite#37]
On these pages:

https://www.ersnet.org/professional-development/fellowships/marie-curie-post-doctoral-research-fellowships-(respire-3)
https://www.ersnet.org/professional-development/fellowships/marie-curie-post-doctoral-research-fellowships-respire-2
https://www.ersnet.org/professional-development/fellowships/marie-curie-post-doctoral-research-fellowships-1st-round-respire-2
https://www.ersnet.org/professional-development/fellowships/marie-curie-post-doctoral-research-fellowships-2nd-round-respire-2
https://www.ersnet.org/professional-development/fellowships/marie-curie-post-doctoral-research-fellowships-3rd-round-respire-2
https://www.ersnet.org/professional-development/fellowships/respire-3-host-application-and-web-registry

The link `Rules and regulation` appears without link! The **conditional statement** should be wrong...

**Comment by tasanoers** [comment]
https://www.ersnet.org/professional-development/fellowships/marie-curie-post-doctoral-research-fellowships-(respire-3)
---->has no document
https://www.ersnet.org/professional-development/fellowships/marie-curie-post-doctoral-research-fellowships-respire-2
---->has no document
https://www.ersnet.org/professional-development/fellowships/marie-curie-post-doctoral-research-fellowships-1st-round-respire-2
---->has no document
https://www.ersnet.org/professional-development/fellowships/marie-curie-post-doctoral-research-fellowships-2nd-round-respire-2
---->has no document
https://www.ersnet.org/professional-development/fellowships/marie-curie-post-doctoral-research-fellowships-3rd-round-respire-2
---->has no document 
https://www.ersnet.org/professional-development/fellowships/respire-3-host-application-and-web-registry
---->has no document
