### ISSUE TITLE
Numbering in article

### ISSUE THREAD

**Issue by bethmaguireeuropeanlung** [EuropeanRespiratorySociety/ERSMainWebsite#4]
On this page the items are all numbered as 1:
![image](https://cloud.githubusercontent.com/assets/21214901/17922491/3922225e-69d7-11e6-90b3-ff1b1f2b6666.png)
I checked in the back office which looked normal but there must be a formatting error somewhere:
![image](https://cloud.githubusercontent.com/assets/21214901/17922508/5ac8d61e-69d7-11e6-85a4-5c897eb49424.png)

**Comment by idealley** [comment]
Actually this subheadings are not lists, thus the `.` should be escaped with `\` . The final numbering looks like:
   ` 1\. the text`

Additionally I have changed the `**title**` which creates bold text to `####` which is a subheading (h4) and is semantically better. 

I have also added the special subheading `#### &nbsp; {.no-break}` to prevent a heading to be at the bottom of the first column. The actual amount of `#` does not matter.
